# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_cours.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_cours(object):
    def setupUi(self, popup_cours):
        popup_cours.setObjectName("popup_cours")
        popup_cours.resize(510, 693)
        self.lineEdit = QtWidgets.QLineEdit(popup_cours)
        self.lineEdit.setGeometry(QtCore.QRect(20, 60, 231, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(popup_cours)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_cours_erreur_numero = QtWidgets.QLabel(popup_cours)
        self.label_cours_erreur_numero.setEnabled(True)
        self.label_cours_erreur_numero.setGeometry(QtCore.QRect(20, 120, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_cours_erreur_numero.setFont(font)
        self.label_cours_erreur_numero.setObjectName("label_cours_erreur_numero")
        self.comboBox_cours = QtWidgets.QComboBox(popup_cours)
        self.comboBox_cours.setGeometry(QtCore.QRect(20, 210, 231, 51))
        self.comboBox_cours.setObjectName("comboBox_cours")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        self.comboBox_cours.setFont(font)
        self.label_2 = QtWidgets.QLabel(popup_cours)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listView_cours = QtWidgets.QListView(popup_cours)
        self.listView_cours.setGeometry(QtCore.QRect(20, 440, 321, 192))
        self.listView_cours.setObjectName("listView_cours")
        self.pushButton_cours_ajouter = QtWidgets.QPushButton(popup_cours)
        self.pushButton_cours_ajouter.setGeometry(QtCore.QRect(20, 340, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_cours_ajouter.setFont(font)
        self.pushButton_cours_ajouter.setObjectName("pushButton_cours_ajouter")

        self.retranslateUi(popup_cours)
        QtCore.QMetaObject.connectSlotsByName(popup_cours)

    def retranslateUi(self, popup_cours):
        _translate = QtCore.QCoreApplication.translate
        popup_cours.setWindowTitle(_translate("popup_cours", "popup_cours"))
        self.label.setText(_translate("popup_cours", "Numéro d\'étudiant"))
        self.label_cours_erreur_numero.setText(_translate("popup_cours", "<html><head/><body><p><span style=\" color:#ff0000;\"> Numéro d\'étudiant invalide. Entrez une valeur numérique.</span></p></body></html>"))
        self.label_2.setText(_translate("popup_cours", "Choix de cours"))
        self.pushButton_cours_ajouter.setText(_translate("popup_cours", "Ajouter"))
